version: 2.1

jobs:
  checkout_and_unit_test:
    machine: true
    steps:
      - run: echo "Hello World!"
  deploy_backend:
    machine: true
    steps:
      - run: echo "Hello World!"
  integration_tests_backend:
    machine: true
    steps:
      - run: echo "Hello World!"
  deploy_staging:
    machine: true
    steps:
      - run: echo "Hello World!"
  acceptance_tests_4:
    machine: true
    steps:
      - run: echo "Hello World!"
  acceptance_tests_3:
    machine: true
    steps:
      - run: echo "Hello World!"
  acceptance_tests_2:
    machine: true
    steps:
      - run: echo "Hello World!"
  acceptance_tests_1:
    machine: true
    steps:
      - run: echo "Hello World!"
  deploy_production:
    machine: true
    steps:
      - run: echo "Hello World!"
workflows:
  monWorkflow:
    jobs:
      - cheackout_and_unit_test
      - deploy_backend:
          requires:
            - cheackout_and_unit_test
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deploy_staging:
          requires:
            - integration_tests_backend
      - acceptance_tests_1:
          requires:
            - deploy_staging
      - acceptance_tests_2:
          requires:
            - deploy_staging
      - acceptance_tests_3:
          requires:
            - deploy_staging
      - acceptance_tests_4:
          requires:
            - deploy_staging
      - deploy_production:
          requires:
            - acceptance_tests_1
            - acceptance_tests_2
            - acceptance_tests_3
            - acceptance_tests_4
